---
# tasks file for firewall

# UBUNTU/DEBIAN

<<<<<<< HEAD
- name: install FW service
=======
- name: installing FW package
>>>>>>> gitlab
  apt: name=ufw state=latest update_cache=yes

- name: start FW service
  systemd: name=ufw state=started enabled=yes

