---
# tasks file for gitlab

#- name: installing packages based on distro
#  include_tasks: "{{ ansible_os_family }}.yml"

- name: install Postfix to send notification emails
  package:
    name: postfix
    state: present

- name: start Postfix
  systemd:
    name: postfix
    state: started
    enabled: yes

- name: add the GitLab package repository and install the package
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
    dest: /tmp
    mode: 0755
   when: ansible_os_family == 'RedHat'

- name: add the GitLab package repository and install the package
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
    dest: /tmp
    mode: 0755
   when: ansible_os_family == 'Debian'

- name: update cache
  package:
    update_cache: yes

- name: install the package
  shell: /tmp/script.rpm.sh

- name: install Gitlab CE
  package:
    name: gitlab-ce
    state: present

