---
# tasks file for gitlab
# https://about.gitlab.com/install/

- name: install Postfix to send notification emails
  package:
    name: postfix
    state: present

- name: start Postfix
  systemd:
    name: postfix
    state: started
    enabled: yes

- block:

  - name: add the GitLab package repository and install the package
    get_url:
      url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
      dest: /tmp
      mode: 0755

  - name: install the package
    shell: /tmp/script.rpm.sh

  when: ansible_os_family == 'RedHat'

- block:

  - name: add the GitLab package repository and install the package
    get_url:
      url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh
      dest: /tmp
      mode: 0755

  - name: install the package
    shell: /tmp/script.deb.sh

  when: ansible_os_family == 'Debian'


# install Gitlab packages

- name: install Gitlab CE
  package:
    name: gitlab-ce
    state: present
  environment:
    EXTERNAL_URL: "http://{{ gitlab_srv }}"

# Gitlab CONFIG

- name: create a backup of config file
  copy:
    src: /etc/gitlab/gitlab.rb
    dest: /etc/gitlab/gitlab.rb.SOURCE
    remote_src: yes

- name: set config file
  copy: 
    src: gitlab.rb
    dest: /etc/gitlab/gitlab.rb

- name: change Gitlab data directory
  file:
    path: /data
    state: directory
    mode: '0755'

- name: fix error during startup
  copy:
    src: "{{ item }}"
    dest: /opt/gitlab/embedded/etc/
  with_items:
  - 90-omnibus-gitlab-kernel.sem.conf
  - 90-omnibus-gitlab-kernel.shmall.conf
  - 90-omnibus-gitlab-kernel.shmmax.conf

- include_tasks: "open-fw-ports.yml"

# configure and start Gitlab service

- name: start Gitlab service (via 'reconfigure')
  shell: gitlab-ctl reconfigure

- name: restart
  systemd:
    name: gitlab-runsvdir.service
    state: restarted
