- name: install required tools
  yum:
    name: "{{ packages }}"
    state: present
  vars: 
    packages:
    - curl
    - policycoreutils-python 
    - openssh-server 
    - ca-certificates

- name: start SSH daemon
  systemd:
    name: sshd
    state: started
    enabled: yes

- include_tasks: "{{ lookup('env','PWD') }}/roles/common/tasks/enable-fw.yml"

- include_tasks: open-fw-ports.yml

