---

- name: installing pgSQL APT GPG key
  apt_key: state=present url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: install pgSQL repo
  shell: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'

- apt: update_cache=yes

- name: installing PostgreSQL
  apt: name={{ item }} update_cache=true state=installed
  with_items:
  - postgresql-{{ tarball }}
  - postgresql-contrib-{{ tarball }}
  - postgresql-client-{{ tarball }}
# - pgadmin4
  - libpq-dev
  - python-psycopg2
  - firewalld
  tags: postgresql

- name: ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

