---

# talk to all hosts just so we can learn about them
- hosts: localhost
  connection: local
  vars:
    cld: alb
    environ: qual
  tasks:
    - include_vars: "~/.config/openstack/vault_{{ cld }}_{{ environ }}.yaml"
    - include_vars: "{{ item }}"
      with_first_found:
        - "vars/{{ ansible_distribution_release }}.yml"
        - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
        - "vars/{{ ansible_distribution }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/default.yml"
      when: vm_user is not defined or vm_os is not defined

### IMPLEMENTED IN THE WRONG WAY: to remove hardcode asap

    - name: terminate 'N' instances
      os_server:
        cloud: "os_{{ cld }}"
        name: "{{ item }}"
        state: "absent"
      with_items:
        - vnf
        - sp
        - intsrv
        - jks

