# CENTOS 7
- name: installing EPEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: installing JDK
  yum: name=java state=present update_cache=yes

- name: removing EPEL
  yum:
    name: epel-release
    state: absent # do not break regular YUM dependencies

- name: set environment variable 'JAVA_HOME'
  shell: "echo 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk' | sudo tee -a /etc/profile"

- name: set environment variable 'JRE_HOME'
  shell: "echo 'export JRE_HOME=/usr/lib/jvm/jre' | sudo tee -a /etc/profile"
