---
- name: remove the Sonata Message Bus (based on RabbitMQ) from the SON-SP VM appliance
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

  # Verify if the Container is running


  # Remove the Sonata BROKER Container (if running)
  - name: destroy the "SP Message Bus"
    docker_container: 
      name: broker
      state: absent
