---

- name: add an APT signing key, uses whichever key is at the URL
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: add specified repository into sources list using specified filename.
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: update repositories cache and install PostgreSQL package
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - "postgresql-{{ tarball }}"
    - "python-psycopg2"

- name: replace line in file examples
  replace: 
    path: "/etc/postgresql/{{ tarball }}/main/postgresql.conf"
    regexp: "#listen_addresses = 'localhost'"
    replace: "listen_addresses = '*'"
    backup: yes
