---
# GUIDE: https://computingforgeeks.com/how-to-install-postgresql-11-on-centos-7/

- name: install the PostgreSQL YUM repo
  yum:
    name: 'https://download.postgresql.org/pub/repos/yum/{{ tarball }}/redhat/rhel-7-x86_64/pgdg-centos{{ pg_ver }}-{{ tarball }}-{{ pg_ver_minor }}.noarch.rpm'
    state: present
    update_cache: yes
# NOTE: change 'roles/pgsql/defaults/main.yml' for a different pgSQL version

- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - "postgresql{{ pg_ver }}-server"
    - "postgresql{{ pg_ver }}"
    - "python-devel"
    - "python-psycopg2"
    - "postgresql{{ pg_ver }}-devel"
#    - libpq-devel

- file: "path=/var/lib/pgsql state=directory owner=postgres group=postgres mode=0775"
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- file: path=/usr/local/pgsql/data state=directory owner=postgres group=postgres mode=0775
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")

- name: initialize PostgreSQL
  shell: "/usr/pgsql-{{ tarball }}/bin/postgresql-{{ pg_ver }}-setup initdb" #-D /var/lib/pgsql/{{ pg_ver }}/data"
  become: yes
  become_user: root
  register: myidentity
# NOTE: 'initdb' must run as 'root'

- name: my secret identity
  debug:
    msg: '{{ myidentity.stdout }}'

- name: start PostgreSQL
# /usr/pgsql-11/bin/pg_ctl -D /var/lib/pgsql/11/data/ -l logfile start
  systemd: name=postgresql-{{ pg_ver }} state=started enabled=yes

