---
# tasks file for KEA

#####
# Sysrepo >0.7.6
#####


#####
# LibYANG >0.16-r2
#####


#####
# GoogleTest >1.8
#####


#####
# KEA
#####

- name: get KEA tarball
  get_url: 
    url: https://ftp.isc.org/isc/kea/1.7.5/kea-1.7.5.tar.gz
    dest: /tmp

- name: unarchive KEA tarball
  unarchive:
    src: /tmp/kea-1.7.5.tar.gz
    dest: /tmp
    remote_src: yes

- name: configure KEA and generate 'make' 
  shell: cd /tmp/kea-1.7.5 && ./configure --prefix=/opt/kea --with-boost-include=/usr/include/boost --with-log4cplus=/opt/log4cplus --with-openssl --with-mysql -with-openssl

- name: compile KEA
  shell: cd /tmp/kea-1.7.5 && make

- name: install KEA
  shell: cd /tmp/kea-1.7.5 && make install


#- name: generate the configure script
#  shell: autoreconf --install

#- name: configure Kea install
#  shell: ./configure --prefix=/opt/kea --with-boost-include=/usr/include/boost --with-log4cplus=/opt/log4cplus --with-openssl --with-mysql -with-openssl

