---
# tasks file for kea

- name: installing KEA DHCPv4 and DHCPv6 server 
  include_tasks: "{{ ansible_distribution }}.yml"

###
# FreeRADIUS client library
###

- name: FreeRADIUS
  block: 

  - name: install FreeRADIUS client library
    git:
      repo: 'https://github.com/FreeRADIUS/freeradius-client.git'
      dest: /tmp/freeradius-client

  - name: configura FreeRADIUS
    shell: cd /tmp/freeradius-client && ./configure --prefix=/usr/local

  - name: compile FreeRADIUS
    shell: cd /tmp/freeradius-client && make

  - name: install FreeRADIUS
    shell: cd /tmp/freeradius-client && make install
    become: true

  when: freeradius_cli == 'true'

###
# NETCONF ver. 1.0.130 (March 2020)
###
#
###
# netconf (RFC-6241) agent
# Netconf provides a framework for the exchange of management information between agents (servers) and clients. 
# The yuma123 agent is a daemon which listens for incoming netconf requests from clients and provides responses. 
# [Homepage:](https://sourceforge.net/projects/yuma123) 
###
# YANG data model (RFC6020)
###

- name: LIBYANG + SYSREPO
  block:

  - name: get LIBYANG tarball
    get_url:
      url: https://github.com/CESNET/libyang/archive/v1.0.130.tar.gz
      dest: /tmp
      mode: '0755'

  - name: unarchive LIBYANG tarball
    unarchive:
      src: /tmp/v1.0.130.tar.gz
      dest: /tmp
      remote_src: yes

  - name: configure LIBYANG and generate 'make'
    shell: cd /tmp/libyang-1.0.130 && mkdir -p build && cd build && cmake ..
    # ```cmake -DPCRE_LIBRARY=/usr/lib64/lipcre.so -DPCRE_INCLUDE_DIR=/usr/include ..```

  - name: compile LIBYANG
    shell: cd /tmp/libyang-1.0.130/build && make

  - name: install LIBYANG
    shell: cd /tmp/libyang-1.0.130/build && make install
    become: true


###
# SYSREPO ver. 1.4.2 (March 2020)
###

  - name: get [SYSREPO](https://www.sysrepo.org/) tarball
    get_url:
      url: https://github.com/sysrepo/sysrepo/archive/v1.4.2.tar.gz
      dest: /tmp
      mode: '0755'

  - name: unarchive SYSREPO tarball
    unarchive:
      src: /tmp/v1.4.2.tar.gz
      dest: /tmp
      remote_src: yes

  - name: install 'clang' (?)
    package:
      name: 
        - clang
        - valgrind
      state: present

  - name: configure SYSREPO and generate 'make'
    shell: cd /tmp/sysrepo-1.4.2 && mkdir -p build && cd build && cmake \
         -DGEN_LANGUAGE_BINDINGS=ON \
         -DGEN_CPP_BINDINGS=OFF \
         -DGEN_PYTHON_BINDINGS=OFF \
         -DGEN_LUA_BINDINGS=OFF \
         -DENABLE_TESTS=OFF \
         -DENABLE_LYD_PRIV=ON \
         -DCMAKE_BUILD_TYPE=Debug \
         -DCMAKE_INSTALL_PREFIX:PATH=/usr \
         -DCMAKE_BUILD_TYPE:String="Release" \
         ..

  - name: compile SYSREPO
    shell: cd /tmp/sysrepo-1.4.2/build && make

  - name: install SYSREPO
    shell: cd /tmp/sysrepo-1.4.2/build && make install
    become: true

  when: libyang == 'true'

###
# [YANG/NETCONF support](https://kea.readthedocs.io/en/kea-1.6.1/arm/netconf.html)
###

###
# KEA ver. 1.7.5 (March 2020)
###

- name: get KEA tarball
  get_url:
    url: https://ftp.isc.org/isc/kea/1.7.5/kea-1.7.5.tar.gz
    dest: /tmp
    mode: '0755'

- name: unarchive KEA tarball
  unarchive:
    src: /tmp/kea-1.7.5.tar.gz
    dest: /tmp
    remote_src: yes

- name: KEA - autoreconfigure
  shell: cd /tmp/kea-1.7.5 && autoreconf -i

- name: configure KEA and generate 'make'
  shell: cd /tmp/kea-1.7.5 && ./configure \
    --prefix=/opt/kea \
    --with-boost-include=/usr/include/x86_64-linux-gnu/ \
    --with-log4cplus=/opt/log4cplus \
    --with-openssl \
    --with-mysql \
    --with-openssl \
    --with-sysrepo
  vars:
    pkg_config_path: /usr/local/lib/
  environment:
    PKG_CONFIG_PATH: '{{ pkg_config_path }}'

- name: compile KEA
  shell: cd /tmp/kea-1.7.5 && make

- name: install KEA
  shell: cd /tmp/kea-1.7.5 && make install

