---
# tasks file for ONOS

- name: install Python bindings to SELinux shared libraries
  yum:
    name: libselinux-python
  when: ansible_os_family == 'RedHat'
- apt:
    name: python-selinux
  when: ansible_os_family == 'Debian'

- name: disable SElinux
  selinux:
    state: disabled

- name: disable Firewall
  include_tasks: "{{ lookup('env','PWD') }}/roles/common/tasks/disable-fw-RedHat.yml"
  when: ansible_os_family == 'RedHat'
- include_tasks: "{{ lookup('env','PWD') }}/roles/common/tasks/disable-fw-Debian.yml"
  when: ansible_os_family == 'Debian'

# For a different ONOS_VERSION, set it at 'roles/onos/defaults/main.yml'
- name: get ONOS tarball from source
  get_url:
    url: "https://repo1.maven.org/maven2/org/onosproject/onos-releases/{{ ONOS_VERSION }}/onos-{{ ONOS_VERSION }}.tar.gz"
    #dest: "/tmp/onos-{{ ONOS_VERSION }}.tar.gz"
    dest: /opt

#- name: copy ONOS tarball to the remote machine
#  copy:
#    src: "/tmp/onos-{{ ONOS_VERSION }}.tar.gz"
#    dest: "/tmp/onos-{{ ONOS_VERSION }}.tar.gz"

#- name: unarchive ONOS tarball on the remote machine
#  unarchive:
#    src: "/tmp/onos-{{ ONOS_VERSION }}.tar.gz"
#    dest: "/opt"
#    remote_src: yes

- name: rename ONOS_HOME directory 
  shell: "mv /opt/onos-{{ ONOS_VERSION }}/* /opt/onos/"

- copy:
    src: /opt/onos/init/onos.initd
    dest: /etc/init.d/onos
    mode: "0755"
    remote_src: yes

- copy:
    src: /opt/onos/init/onos.service
    dest: /etc/systemd/system/
    mode: "0755"
    remote_src: yes

- name: Ensure group 'sdn' exists
  group:
    name: sdn
    state: present

- name: Add the user 'sdn' with 'system' privileges
  user:
    name: sdn
    state: present
    comment: ´SDN system user'
    system: true

- name: Recursively change ownership of a directory
  file:
    path: /opt/onos
    state: directory
    recurse: yes
    mode: "0755"
    owner: sdn
    group: sdn

- name: start ONOS
  systemd:
    name: onos
    state: restarted
    daemon_reload: yes
    enabled: yes

