---

# talk to all hosts just so we can learn about them
- hosts: localhost
  connection: local
  tasks:
    - include_vars: "environments/{{ environ }}/group_vars/vault.yml"

    - name: launch 'N' instances
      os_server:
        auth:
          auth_url: "{{ os_auth_url }}"
          username: "{{ os_user }}"
          password: "{{ os_pswd }}"
          project_name: "{{ os_proj}}"
        name: "{{ prefix }}-{{ item.name }}"
        state: present
        key_name: "{{ item.key }}"
        availability_zone: "{{ item.availability_zone }}"
        nics: "{{ item.nics }}"
        image: "{{ item.image }}"
        flavor: "{{ item.flavor }}"
      with_items: "{{ servers }}"
      register: "os_hosts"

    - name: OPTION1 - create in-memory Inventory
      add_host:
        name: "{{ item['openstack']['human_id'] }}"
        groups: "{{ item['item']['meta']['group'] }}"
        ansible_host: "{{ item.openstack.accessIPv4 }}"
      with_items: "{{ os_hosts.results }}"
      register: "aresult"

# CREDITS: this playbook follows and extends [Ansible - Create OpenStack servers with Ansible 2.0 and the os_server module and a dynamic inventory](https://raymii.org/s/tutorials/Ansible_-_create_OpenStack_servers_with_os_server.html), by Remi van Elst

    - name: OPTION2 - create static Inventory
      template: 
        src: ansible-hosts.j2
        dest: "./environments/{{ environ }}/hosts"
