---

- hosts: www
  remote_user: centos
  become: true
  connection: ssh
  roles:
    - ~/ansible/utils/roles/nginx

- hosts: db
  remote_user: centos
  become: true
  connection: ssh
  roles:
    - ~/ansible/utils/roles/pgsql

