mkdir environments
mkdir environments/dev
mkdir environments/dev/group_vars
touch environments/dev/group_vars/all
touch environments/dev/group_vars/vault
mkdir environments/dev/host_vars
touch environments/dev/hosts
mkdir environments/int
mkdir environments/int/group_vars
touch environments/int/group_vars/all
touch environments/int/group_vars/vault
mkdir environments/int/host_vars
touch environments/int/hosts
mkdir environments/qual
mkdir environments/qual/group_vars
touch environments/qual/group_vars/all
touch environments/qual/group_vars/vault
mkdir environments/qual/host_vars
touch environments/qual/hosts
mkdir environments/demo
mkdir environments/demo/group_vars
touch environments/demo/group_vars/all
touch environments/demo/group_vars/vault
mkdir environments/demo/host_vars
touch environments/demo/hosts

