---
# tasks file for pip

- name: install PIP
  apt:
    name: [ libssl-dev, libffi-dev, python-dev, python-pip ]
    state: present

- name: upgrade PIP
  pip:
    name: pip
    extra_args: "--upgrade"
    state: present
