---
# tasks file for pip

  # We recommend disabling EPEL when using RDO packages \
  # due to updates in EPEL breaking backwards compatibility. \
  # Or, preferably pin package versions using the 'yum-versionlock' plugin

- name: PIP is not available in CentOS 7 core repositories, we need to enable EPEL
  yum:
    name: [epel-release, python-pip, python-devel]
    state: present

- name: uninstall EPEL
  yum: 
    name: epel-release
    state: absent

#- name: install the 'Development tools' package group
#  yum:
#    name: "@Development tools"
#    state: present
