---

# talk to all hosts just so we can learn about them
- hosts: localhost
  connection: local
  tasks:
    - include_vars: "~/.config/openstack/os_ptin_{{ environ }}_vault.yml"

    - name: launch 'N' instances
      os_server:
        cloud: os_cloud
        name: "{{ prefix }}-{{ item.name }}"
        state: present
        key_name: "{{ item.key }}"
        availability_zone: "{{ item.availability_zone }}"
        security_groups: son-dev-secgrp
        nics: "{{ item.nics }}"
        image: "{{ item.image }}"
        flavor: "{{ item.flavor }}"
      with_items: "{{ servers }}"
      register: "os_hosts"

    - name: create in-memory Inventory # temporary in-memory group of hosts that only persists until the end of the playbook (to be used in the next task)
      add_host:
        name: "{{ item.openstack.human_id }}"
        groups: "{{ item.item.meta.group }}"
        ansible_host: "{{ item.openstack.accessIPv4 }}"
      with_items: "{{ os_hosts.results }}"

    - name: create static Inventory based on a provided Template ['jinja2'](http://docs.ansible.com/ansible/template_module.html)
      template: 
        src: inventory_template.j2
        dest: "./hosts"

#    - name: Wait for SSH on the Instance
#      command: >
#        ssh -oBatchMode=yes -oStrictHostKeyChecking=no -i ~/.ssh/{{ item.openstack.key_name }}.pem ubuntu@{{ item.openstack.accessIPv4 }} true
##      register: result
#      until: result|success
#      retries: 30
#      delay: 10
#      with_items: "{{ os_hosts.results }}"

- hosts: www
  remote_user: ubuntu
  become: true
  roles:
    - nginx

- hosts: db
  remote_user: ubuntu
  become: true
  roles:
    - pgsql
