---

- name: Install Erlang from the EPEL repository
  yum: name=erlang state=present update_cache=true

#- name: checking if SELinux authorizes rabbitmq_port_t to tcp 25672
#  shell: /usr/sbin/semanage port --list | grep "rabbitmq_port_t.*tcp.25672"
#  register: selinux_port_check
#  ignore_errors: true

#­ name: adding the port to SELinux managed port if needed
#  shell: /usr/sbin/semanage port ­a ­t rabbitmq_port_t ­p tcp 25672
#  when: selinux_port_check|failed

- name: SELinux (temporarily) disabled
  selinux: policy=targeted state=permissive

#- name: Import RabbitMQ signing key
#  command: rpm --import https://www.rabbitmq.com/rabbitmq-release-signing-key.asc

- name: Install RabbitMQ server
  yum: name=rabbitmq-server state=present update_cache=yes disable_gpg_check=yes
#    gpgkey: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc

- name: Start RabbitMQ server
  service: name=rabbitmq-server state=started enabled=yes
