---
# tasks file for rabbitmq

- include: centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- include: trusty.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

- include: xenial.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16"

