---

- name: install tools to manage SELinux on Redhat/CentOS machine
  yum: name={{ item }} state=present
  with_items:
#  - libselinux-python
#  - libsemanage-python
  - libsemanage-devel
  - policycoreutils-python

- name: enable MongoDB ports on SELinux enforcing mode
  command: 'semanage port -a -t mongod_port_t -p tcp 27017'

- name: enable MongoDB web status port on SELinux enforcing mode
  command: 'semanage port -a -t mongod_port_t -p tcp 28017'

- name: add MongoDB 3.+ repo to YUM
  copy: src=~/ansible/roles/mongo/files/mongodb-org-3.2.repo dest=/etc/yum.repos.d/mongodb-org-3.2.repo owner=root group=root mode=0644

- name: install MongoDB to CentOS7
  yum: name=mongodb-org state=present update_cache=yes

