---
- name: destroying a VM via Ansible Cloud Module for Openstack
  hosts: localhost
  connection: local
  tasks:

  - include_vars: vars/defaults.yml

  - name: remove an Openstack 'nova-compute' instance
    os_server:
      state: absent
      cloud: os_ptin # ~/.config/openstack/os_ptin_qual_vault.yaml
      name: "{{ vm_name_prefix }}-{{ item }}"
    with_sequence: count={{ nbofvms }}
