---
- name: remove Docker containers from the SP VM
  hosts: "{{ target }}"
  become: true
  tasks:

# Removing the Sonata MONITORY Docker Images

  - name: MONIT InfluxDB - removing Docker containers
    docker_container:
      name: son-monitor-influxdb
      image: sonatanfv/son-monitor-influxdb
      state: absent

  - name: MONIT MySQL - removing Docker containers
    docker_container:
      name: son-monitor-mysql
      state: absent

  - name: MONIT Push Gateway - removing Docker containers
    docker_container:
      name: son-monitor-pushgateway
      state: absent

  - name: MONIT PROMETHEUS - removing Docker containers
    docker_container:
      name: son-monitor-prometheus
      state: absent

  - name: MONIT MANAGER - removing Docker containers
    docker_container:
      name: son-monitor-manager
      state: absent

  - name: MONIT Probe - removing Docker containers
    docker_container:
      name: son-monitor-probe
      state: absent
