---
- name: deploy MANO FRAMEWORK as Docker containers from private Registry to the SP VM appliance
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

# Running the Sonata MANO Docker Images

  - name: MANO Plug-in Manager - running Docker containers
    docker_container:
      name: pluginmanager
      image: sonatanfv/pluginmanager
      env:
        mongo_host: "{{ ansible_eth0.ipv4.address }}"
        broker_host: amqp://guest:guest@{{ ansible_eth0.ipv4.address }}:5672/%2F
      state: started
      ports: 8001:8001

#  - pause: seconds=15

  - name: MANO Service Life-cycle Management (SLM) - running Docker containers
    docker_container:
      name: servicelifecyclemanagement
      image: sonatanfv/servicelifecyclemanagement
      env:
        url_nsr_repository: http://{{ ansible_eth0.ipv4.address }}:4002/records/nsr/
        url_vnfr_repository: http://{{ ansible_eth0.ipv4.address }}:4002/records/vnfr/
        url_monitoring_server: http://{{ ansible_eth0.ipv4.address }}:8000/api/v1/
        broker_host: amqp://guest:guest@{{ ansible_eth0.ipv4.address }}:5672/%2F
      state: started

#  - name: MANO Function Life-cycle Management (FML) - running Docker containers
#    docker_container:
#      name: functionlifecyclemanagement
#      image: sonatanfv/functionlifecyclemanagement
#      state: started
#      # ports:

  - name: MANO Infrastructure Abstractor - running Docker containers
    docker_container:
      name: son-sp-infrabstract
      image: sonatanfv/son-sp-infrabstract
      state: started
      env:
        broker_host: "{{ ansible_eth0.ipv4.address }}"
        broker_url: "amqp://guest:guest@{{ ansible_eth0.ipv4.address }}/%2F"
        broker_uri: "amqp://guest:guest@{{ ansible_eth0.ipv4.address }}:5672/%2F"
        repo_host: "{{ ansible_eth0.ipv4.address }}"
        repo_port: "5432"
        repo_user: "sonatatest"
        repo_pass: "sonata"
