- name: install Apache2
  yum: name=httpd update_cache=yes state=latest

- name: starting the Apache service
  service: name=httpd state=started enabled=yes


- name: install 'firewalld' to manage arbitrary ports/services
  yum: name=firewalld state=latest

- name: starting the FW service
  service: name=firewalld state=started enabled=yes

