---
# tasks file for freeradius-client

####
# FreeRADIUS client library
####

- name: install FreeRADIUS client library
  git:
    src: https://github.com/fxdupont/freeradius-client.git
    dest: /tmp

- name: configura FreeRADIUS 
  shell: cd /tmp/freeradius-client/ && ./configure

- name: compile FreeRADIUS
  shell: cd /tmp/freeradius-client/ && make

- name: install FreeRADIUS
  shell: cd /tmp/freeradius-client/ && make install
