---
# tasks file for freeradius-client

###
# FreeRADIUS client library
###

- name: install FreeRADIUS client library
  git:
    repo: 'https://github.com/fxdupont/freeradius-client.git'
    dest: /tmp/freeradius-client

- name: configura FreeRADIUS 
  shell: cd /tmp/freeradius-client && ./configure --prefix=/usr/local

- name: compile FreeRADIUS
  shell: cd /tmp/freeradius-client && make

- name: install FreeRADIUS
  shell: cd /tmp/freeradius-client && make install
  become: true

