---
# tasks file for boost

#####
# [portable C++ BOOST library](https://www.boost.org/doc/libs/1_72_0/more/getting_started/unix-variants.html)
#####

- name: install an up-to-date version of [C++ Boost library](http://www.boost.org/more/getting_started/unix-variants.html)
  get_url:
    url: "https://dl.bintray.com/boostorg/release/{{ BOOST_VER }}/source/boost_{{ BOOST_VERSION }}.tar.gz
    dest: /tmp

- name: extract Boost tarball
  unarchive:
    src: /tmp/boost_1_72_0.tar.gz
    dest: /tmp

- name: boostrap Boost library
  shell: cd /tmp/boost_1_72_0 && ./bootstrap.sh # defaults to '/usr/local/', use '--prefix=/opt/boost' to change it.
- shell: cd /tmp/boost_1_72_0 && ./b2 headers
- shell: cd /tmp/boost_1_72_0 && ./b2 install --with=all

