---
# tasks file for boost

#####
# [portable C++ BOOST library](https://www.boost.org/doc/libs/1_72_0/more/getting_started/unix-variants.html)
#####

- name: install latest version of [C++ Boost library](http://www.boost.org/more/getting_started/unix-variants.html)
  get_url:
    url: "https://dl.bintray.com/boostorg/release/{{ BOOST_VER }}/source/boost_{{ BOOST_VERSION }}.tar.gz"
    dest: /tmp

- name: extract Boost tarball
  unarchive:
    src: "/tmp/boost_{{ BOOST_VERSION }}.tar.gz"
    dest: /tmp

- name: boostrap Boost library
  shell: "cd /tmp/boost_{{ BOOST_VERSION }} && ./bootstrap.sh" # defaults to '/usr/local/', use '--prefix=/opt/boost' to change it.
- shell: "cd /tmp/boost_{{ BOOST_VERSION }} && ./b2 headers"
- shell: "cd /tmp/boost_{{ BOOST_VERSION }} && ./b2 install"   # --with=all

