---
- name: deploy FluentD to the target machine
  hosts: "{{ target | default('localhost') }}"
  become: true

  pre_tasks:
    - debug: msg="##### start FluentD deployment {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
    - file:
        path: ansible.log
        state: touch

  roles:
    - fluentd

  post_tasks:
    - debug: msg="##### ending FluentD deployment {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"

