---
- name: deploy KEA to the target machine
  hosts: "{{ target | default('localhost') }}"
  become: true
  pre_tasks:
    - requirements.yml
  roles:
    - { role: gcc, GCC_VER: 9.3.0 }
    - { role: boost, BOOST_VER: 1.72.0 }
    - freeradius-client
    - sysrepo
    - kea

