---
- name: deploy KEA to the target machine
  hosts: "{{ target | default('localhost') }}"
  become: true
  pre_tasks:
    - kea_requirements.yml
  roles:
    - { role: gcc, GCC_VER: "{{ GCC_VER }}"
    - { role: boost, BOOST_VER: "{{ BOOST_VER }}"
    - freeradius-client
    - kea

