---
- name: deploy NTP and synch the target machine 
  hosts: "{{ target | default('localhost') }}"
  become: true

  pre_tasks:
    - debug: msg="##### start NTP deployment {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"

    - file:
        path: "{{ lookup('env','HOME') }}/ansible.log"
        state: touch
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: "u=rw,g=rw,o=rw"

  roles:
    - ntp

  post_tasks:
    - debug: msg="##### ending NTP deployment {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"

