---

# HOW-TO-USE EXAMPLE:
# pgSQL11 (latest): $ ansible-playbook utils/deploy/pgsql.yml -v"
# pgSQL9.6: $ ansible-playbook utils/deploy/pgsql.yml -e "tarball=9.6 tarball_ver=96 pg_ver=9.6-3" -v

- name: installing a PostgreSQL database server
  hosts: "{{ target | default('localhost') }}"
  #remote_user: "{{ }}"
  become: true 
  roles:
  - common
  - pgsql
