---
# files for Apache

- include: "{{ ansible_distribution_release }}.yml"

# Managing firewall

- name: starting 'firewalld' service
  service: name=firewalld state=started

- name: open WWW listening port at FW
  firewalld: port=80/tcp permanent=true state=enabled
  notify: reload firewalld

