- name: Create a directory if it does not exist
  file:
    path: "{{ lookup('env','HOME') }}/.config/openstack"
    state: directory
    mode: '0755'

- name: Copy file with owner and permissions
  copy:
    src: "{{ lookup('env','PWD') }}/roles/osc/files/clouds.yaml"
    dest: "{{ lookup('env','HOME') }}/.config/openstack"
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    mode: '0644'

- name: create a new security group for VM connectivity
  os_security_group:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: "{{ plat }}-secgrp"
    description: Jenkins ports

- name: create a security rule on that group to allow any SSH connection
  os_security_group_rule:
    cloud: "os_{{ pop }}_{{ proj }}"
    security_group: "{{ plat }}-secgrp"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0

