---
# tasks file for JENKINS

- name: installing pre-required packages based on distro
  include_tasks: "{{ ansible_os_family }}.yml"

- name: installing Jenkins package
  package:
    name:
      - java
      - jenkins
    state: latest

- name: start JENKINS service
  systemd:
    state: started
    name: jenkins
    enabled: yes
    daemon_reload: yes

- name: Openstack modules require OSC
  include_tasks: secgrp.yml

