# CENTOS 7
# install guide: "Installing Jenkins on Red Hat distributions", Feb 2018
# URL: https://wiki.jenkins.io/display/JENKINS/Installing+Jenkins+on+Red+Hat+distributions

- name: installing Jenkins YUM GPG key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install Jenkins repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: 0644

# Install Firewalld and open FW ports

- name: install Firewalld
  include_tasks: "{{ lookup('env','PWD') }}/roles/common/tasks/enable-fw-{{ ansible_os_family }}.yml"

- name: open Jenkins default port (8080) at CentOS/Redhat machine
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
  notify: reload firewalld
