#- name: use Openstack command line clients to check if Security Group exists
#  shell: openstack --os-cloud "os_{{ pop }}_{{ proj }}" security group list
#  register: os_secgrp

- name: create a security group for JENKINS connections
  os_security_group:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: "{{ plat }}-secgrp"
    description: open Jenkins ports
  become_user: "{{ lookup('env','USER') }}"

- name: create a security rule to allow JENKINS client connections
  os_security_group_rule:
    cloud: "os_{{ pop }}_{{ proj }}"
    security_group: "{{ plat }}-secgrp"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0
  become_user: "{{ lookup('env','USER') }}"

