---
- name: deploy Docker Images from Hub to CentOS and Ubuntu machines
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

  - name: deploy CentOS 7 Docker Image from Hub to a running VM 
    docker: 
      name: CentOS7
      image: centos:latest
      state: started
      
  - name: deploy Ubuntu 16.04 Docker Image from Hub to a running VM
    docker:
      name: Ubuntu16
      image: ubuntu:latest
      state: started

