---
- name: deploy Gitlab to the target machine
  hosts: "{{ target | default('localhost') }}"
  gather_facts: yes
  become: true
  tasks:

  - name: remove Gitlab CE
    package: 
      name: gitlab-ce
      state: absent
  
  - name: remove Postfix
    package: 
      name: postfix
      state: absent

  - block:

    - name: remove Gitlab from repos cache
      file:
        name: /etc/yum.repos.d/gitlab_gitlab-ce.repo
        state: absent

    - name: remove temp file
      file:
        name: /tmp/script.rpm.sh 
        state: absent

    when: ansible_os_family == 'RedHat'

  - block: 

    - name: remove Gitlab from repos cache
      file:
        name: /etc/apt/sources.list.d/gitlab_gitlab-ce.repo
        state: absent

    - name: remove temp file
      file:
        name: /tmp/script.deb.sh 
        state: absent

    when: ansible_os_family == 'Debian'
