---

# HOW TO USE: ```$ ansible-playbook utils/destroy/gitlab.yml -v```

- name: remove Gitlab CI/CD server
  hosts: "{{ target | default('localhost') }}"
  become: true 
  tasks:

  - name: stop Gitlab service
    shell: gitlab-ctl stop
    ignore_errors: true

  - name: stop Gitlab service (... just in case)
    systemd:
      name: gitlab-runsvdir.service
      state: stopped
    ignore_errors: true

  - name: remove previous Gitlab installation
    package:
      name: "{{ item }}"
      state: absent
    with_items:
    - gitlab-ce
    - gitlab-runner
    ignore_errors: true

  - name: Recursively remove directories
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "/opt/gitlab"
    - "/etc/gitlab"
    - "/var/log/gitlab"
    - "/usr/bin/gitlab*"
