---

# HOW TO USE - EXAMPLES: 
# ansible-playbook utils/destroy/onos.yml -v 
# ansible-playbook utils/destroy/onos.yml -v

- name: remove ONOS database server
  hosts: "{{ target | default('localhost') }}"
  become: true 
  tasks:

  - name: get service facts
    service_facts:

#   - name: try to work out how to access the service
#     debug:
#       var: ansible_facts.services['onos.service']

  - name: stop ONOS
    systemd:
      name: onos
      state: stopped
    when: ansible_facts.services['onos.service'] is defined and ansible_facts.services['onos.service'].state == 'running'
    #when: hostvars[inventory_hostname]['services']['onos.service'].['state'] == running

  - name: remove previous ONOS installation
    yum:
      name: onos
      state: absent

  - name: Recursively remove directory
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "/opt/onos"
    - "/etc/onos"
