---

- name: remove ONOS database server
  hosts: "{{ target | default('localhost') }}"
  become: true 
  tasks:

  - name: stop ONOS
    systemd:
      name: onos
      state: stopped
    when: ansible_facts.services['onos.service'] is defined and ansible_facts.services['onos.service'].state == 'running'

  - name: remove previous ONOS installation
    package:
      name: onos
      state: absent

  - include_vars: "{{ lookup('env','PWD') }}/roles/onos/vars/main.yml"

  - name: Recursively remove directory
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "/opt/onos"
    - "/opt/onos-{{ ONOS_VERSION }}"
    - "/etc/init.d/onos"
    - "/etc/systemd/system/onos.service"
