---

# HOW TO USE - EXAMPLES: 
# ansible-playbook utils/destroy/pgsql.yml -v 
# ansible-playbook utils/destroy/pgsql.yml -e "tarball=11 pg_ver=11" -v

- name: remove PostgreSQL database server
  hosts: "{{ target | default('localhost') }}"
  become: true 
  tasks:

  - name: stop PostgreSQL
    systemd:
      name: "postgresql-{{ pg_ver }}"
      state: stopped

  - name: remove previous pgSQL install
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - "postgresql{{ pg_ver }}-server"
      - "postgresql{{ pg_ver }}-libs"
      - "postgresql{{ pg_ver }}"
      - "postgresql{{ pg_ver }}-devel"
      - "libpq-devel"
      - "python-psycopg2"


  - name: Recursively remove directory
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "/var/lib/pgsql/{{ pg_ver }}"
    - "/usr/pgsql-{{ tarball }}"
    - "/etc/postgresql/{{ tarball }}"
