---
# tasks file for openstackclients

#NOTE: Shade has been superceded by 'openstacksdk'

- name: enable RDO repository (to install OSC packages)
  yum: 
    name: https://rdoproject.org/repos/rdo-release.rpm
    state: present

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install Openstack command line clients
  yum: 
    name:
      - python-openstackclient
      - python-keystoneclient
      - python-heatclient
      - python-glanceclient
      - python-cinderclient
      - python-swiftclient
      - python-novaclient
      - python-neutronclient
    state: present
