---
- name: create a MongoDB for the target machine
  hosts: "{{ target }}"
  become: true
  tasks:
  - name: deploy MongoDB container for Monitory
    docker_container:
      name: son-mongo
      image: sonatanfv/son-mongo
      #env:
      state: started
      ports: 27017:27017
      volumes:
        - /var/log/sonata:/var/log/mongo
