---

- name: Install YUM Firewalld
  yum:
    name: firewalld
    state: present

- name: restart service Firewalld, in all cases, also issue daemon-reload to pick up config changes
  systemd:
    state: restarted
    daemon_reload: yes
    name: firewalld


