---
- name: UNINSTALLING MongDB database server
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

  - name: check if the MongoDB service exists
    stat: path=/etc/init.d/mongod
    register: service_status

  - name: previously assure that MongoDB is not running
    service: name=mongod state=stopped
    when: service_status.stat.exists
    register: service_stopped

  - name: ensure the MongoDB service is stopped
    service: name=mongod state=stopped enabled=no

  - name: removing packages
    apt: name={{ item }} update_cache=true purge=yes state=absent
    with_items:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-mongos
    - mongodb-org-shell
    - mongodb-org-tools
    when: ansible_distribution == "Ubuntu"

  - name: removing datafiles
    file: path={{ item }} state=absent
    with_items:
    - /var/lib/mongodb/
    - /var/log/mongodb/
    - /etc/mongodb/

