---
- name: deploy TERRAFORM to the SON-SP VM appliance
  hosts: "{{ targets }}"
  sudo: yes
  tasks:

  - name: get zip file from URL
    get_url: url=https://releases.hashicorp.com/terraform/0.6.16/terraform_0.6.16_linux_amd64.zip dest=/opt/terraform
