---

- name: install Docker dependency libraries
  yum: name={{ item }} state=present update_cache=yes
  with_items:
  - git
  - python-pip

- name: add Docker repo to YUM
  copy: src=/home/ptin_admin/ansible/roles/docker/files/docker.repo dest=/etc/yum.repos.d/docker.repo owner=root group=root mode=0644

- name: install Docker on CentOS7
  yum: name=docker-engine state=present update_cache=yes

- name: add user to Docker group
  user: name=ptin_admin shell=/bin/bash groups=docker append=yes

- name: "Configuring Docker Options"
  copy: src=/home/ptin_admin/ansible/roles/docker/files/docker.conf dest=/etc/sysconfig/docker owner=root group=root mode=0644
#  copy: src=/home/ptin_admin/ansible/roles/docker/files/docker dest=/etc/default/docker owner=root group=root mode=0644
#  notify:
#  - restart docker

- name: start Docker daemon
  service: name=docker state=restarted enabled=yes
