---
# tasks file for JENKINS

- name: installing JENKINS on CentOS 7
  include: "{{ ansible_distribution_release }}.yml"
  when: ansible_os_family == "RedHat"

- name: installing JENKINS on Debian systems
  include: debian.yml
  when: ansible_os_family == "Debian"

# Managing firewall
- name: start 'firewalld' service 
  service: name=firewalld state=started

- name: open Jenkins listening port at fw
  firewalld: port=8080/tcp permanent=true state=enabled
  notify: reload firewall

