---
# tasks file for mysql
- name: installing MYSQL for CentOS
  include: centos.yml
  when: ansible_os_family == "RedHat"
 
- name: installing MYSQL for Ubuntu
  include: ubuntu.yml
  when: ansible_os_family == "Debian"

